#write.csv(nisALL4, file = "nisFull.csv")
#NEW JERSEY ALONE
agg3$NJ<- plyr::revalue(agg3$STATE, c("ALABAMA"= 0,
                                              "ALASKA"= 0,
                                              "ARIZONA"=0,
                                              "ARKANSAS"=0,
                                              "CALIFORNIA"=0,
                                              "COLORADO"=0,
                                              "CONNECTICUT"=0,
                                              "DELAWARE"=0,
                                              "DISTRICT OF COLUMBIA"=0,
                                              "FLORIDA"=0,
                                              "GEORGIA"=0,
                                              "HAWAII"=0,
                                              "IDAHO"=0,
                                              "ILLINOIS"=0,
                                              "INDIANA"=0,
                                              "IOWA"=0,
                                              "KANSAS"=0,
                                              "KENTUCKY"=0,
                                              "LOUISIANA"=0,
                                              "MAINE"=0,
                                              "MARYLAND"=0,
                                              "MASSACHUSETTS"=0,
                                              "MICHIGAN"=0,
                                              "MINNESOTA"=0,
                                              "MISSISSIPPI"=0,
                                              "MISSOURI"=0,
                                              "MONTANA"=0,
                                              "NEBRASKA"=0,
                                              "NEVADA"=0,
                                              "NEW HAMPSHIRE"=0,
                                              "NEW JERSEY"=1,
                                              "NEW MEXICO"=0,
                                              "NEW YORK"=0,
                                              "NORTH CAROLINA"=0,
                                              "NORTH DAKOTA"=0,
                                              "OHIO"=0,
                                              "OKLAHOMA"=0,
                                              "OREGON"=0,
                                              "PENNSYLVANIA"=0,
                                              "RHODE ISLAND"=0,
                                              "SOUTH CAROLINA"=0,
                                              "SOUTH DAKOTA"=0,
                                              "TENNESSEE"=0,
                                              "TEXAS"=0,
                                              "UTAH"=0,
                                              "VERMONT"=0,
                                              "VIRGINIA"=0,
                                              "WASHINGTON"=0,
                                              "WEST VIRGINIA"=0,
                                              "WYOMING"=0,
                                              "WISCONSIN"=0,
                                              "GUAM"=0, 
                                              "U.S.  VIRGIN ISLANDS"=0,
                                              "PUERTO RICO"=0))
agg3$NJ<-as.numeric(as.character(agg3$NJ))
agg3$POST<-ifelse(agg3$YEAR >= 2011, 1,0)
agg3$DIDNJ <-agg3$POST*agg3$NJ
DIDREG8 <- lm(BF_ENDR06 ~ POST + NJ + DIDNJ, data = agg3)
summary(DIDREG8) 


#CA ALONE
agg3$CA<- plyr::revalue(agg3$STATE, c("ALABAMA"= 0,
                                              "ALASKA"= 0,
                                              "ARIZONA"=0,
                                              "ARKANSAS"=0,
                                              "CALIFORNIA"=1,
                                              "COLORADO"=0,
                                              "CONNECTICUT"=0,
                                              "DELAWARE"=0,
                                              "DISTRICT OF COLUMBIA"=0,
                                              "FLORIDA"=0,
                                              "GEORGIA"=0,
                                              "HAWAII"=0,
                                              "IDAHO"=0,
                                              "ILLINOIS"=0,
                                              "INDIANA"=0,
                                              "IOWA"=0,
                                              "KANSAS"=0,
                                              "KENTUCKY"=0,
                                              "LOUISIANA"=0,
                                              "MAINE"=0,
                                              "MARYLAND"=0,
                                              "MASSACHUSETTS"=0,
                                              "MICHIGAN"=0,
                                              "MINNESOTA"=0,
                                              "MISSISSIPPI"=0,
                                              "MISSOURI"=0,
                                              "MONTANA"=0,
                                              "NEBRASKA"=0,
                                              "NEVADA"=0,
                                              "NEW HAMPSHIRE"=0,
                                              "NEW JERSEY"=0,
                                              "NEW MEXICO"=0,
                                              "NEW YORK"=0,
                                              "NORTH CAROLINA"=0,
                                              "NORTH DAKOTA"=0,
                                              "OHIO"=0,
                                              "OKLAHOMA"=0,
                                              "OREGON"=0,
                                              "PENNSYLVANIA"=0,
                                              "RHODE ISLAND"=0,
                                              "SOUTH CAROLINA"=0,
                                              "SOUTH DAKOTA"=0,
                                              "TENNESSEE"=0,
                                              "TEXAS"=0,
                                              "UTAH"=0,
                                              "VERMONT"=0,
                                              "VIRGINIA"=0,
                                              "WASHINGTON"=0,
                                              "WEST VIRGINIA"=0,
                                              "WYOMING"=0,
                                              "WISCONSIN"=0,
                                              "GUAM"=0, 
                                              "U.S.  VIRGIN ISLANDS"=0,
                                              "PUERTO RICO"=0))
agg3$CA<-as.numeric(as.character(agg3$CA))
agg3$POST<-ifelse(agg3$YEAR >= 2006, 1,0)
agg3$DIDCA <-agg3$POST*agg3$CA
DIDREG9 <- lm(BF_ENDR06 ~ POST + CA + DIDCA + `INCPOV1.BELOW POVERTY`, data = agg3)
summary(DIDREG9) 

#FULL SAMPLE NJ ONLY
nisALL3$NJ<- plyr::revalue(nisALL3$STATE, c("ALABAMA"= 0,
                                      "ALASKA"= 0,
                                      "ARIZONA"=0,
                                      "ARKANSAS"=0,
                                      "CALIFORNIA"=0,
                                      "COLORADO"=0,
                                      "CONNECTICUT"=0,
                                      "DELAWARE"=0,
                                      "DISTRICT OF COLUMBIA"=0,
                                      "FLORIDA"=0,
                                      "GEORGIA"=0,
                                      "HAWAII"=0,
                                      "IDAHO"=0,
                                      "ILLINOIS"=0,
                                      "INDIANA"=0,
                                      "IOWA"=0,
                                      "KANSAS"=0,
                                      "KENTUCKY"=0,
                                      "LOUISIANA"=0,
                                      "MAINE"=0,
                                      "MARYLAND"=0,
                                      "MASSACHUSETTS"=0,
                                      "MICHIGAN"=0,
                                      "MINNESOTA"=0,
                                      "MISSISSIPPI"=0,
                                      "MISSOURI"=0,
                                      "MONTANA"=0,
                                      "NEBRASKA"=0,
                                      "NEVADA"=0,
                                      "NEW HAMPSHIRE"=0,
                                      "NEW JERSEY"=1,
                                      "NEW MEXICO"=0,
                                      "NEW YORK"=0,
                                      "NORTH CAROLINA"=0,
                                      "NORTH DAKOTA"=0,
                                      "OHIO"=0,
                                      "OKLAHOMA"=0,
                                      "OREGON"=0,
                                      "PENNSYLVANIA"=0,
                                      "RHODE ISLAND"=0,
                                      "SOUTH CAROLINA"=0,
                                      "SOUTH DAKOTA"=0,
                                      "TENNESSEE"=0,
                                      "TEXAS"=0,
                                      "UTAH"=0,
                                      "VERMONT"=0,
                                      "VIRGINIA"=0,
                                      "WASHINGTON"=0,
                                      "WEST VIRGINIA"=0,
                                      "WYOMING"=0,
                                      "WISCONSIN"=0,
                                      "GUAM"=0, 
                                      "U.S.  VIRGIN ISLANDS"=0,
                                      "PUERTO RICO"=0))
nisALL3$NJ<-as.numeric(as.character(nisALL3$NJ))
nisALL3$POST<-ifelse(nisALL3$YEAR >= 2011, 1,0)
nisALL3$DIDNJ <-nisALL3$POST*nisALL3$NJ
DIDREG10 <- lm(BF_ENDR06 ~ POST + NJ + DIDNJ, data = nisALL3)
summary(DIDREG10) 


#FULL SAMPLE CA ONLY
nisALL3$CA<- plyr::revalue(nisALL3$STATE, c("ALABAMA"= 0,
                                            "ALASKA"= 0,
                                            "ARIZONA"=0,
                                            "ARKANSAS"=0,
                                            "CALIFORNIA"=1,
                                            "COLORADO"=0,
                                            "CONNECTICUT"=0,
                                            "DELAWARE"=0,
                                            "DISTRICT OF COLUMBIA"=0,
                                            "FLORIDA"=0,
                                            "GEORGIA"=0,
                                            "HAWAII"=0,
                                            "IDAHO"=0,
                                            "ILLINOIS"=0,
                                            "INDIANA"=0,
                                            "IOWA"=0,
                                            "KANSAS"=0,
                                            "KENTUCKY"=0,
                                            "LOUISIANA"=0,
                                            "MAINE"=0,
                                            "MARYLAND"=0,
                                            "MASSACHUSETTS"=0,
                                            "MICHIGAN"=0,
                                            "MINNESOTA"=0,
                                            "MISSISSIPPI"=0,
                                            "MISSOURI"=0,
                                            "MONTANA"=0,
                                            "NEBRASKA"=0,
                                            "NEVADA"=0,
                                            "NEW HAMPSHIRE"=0,
                                            "NEW JERSEY"=0,
                                            "NEW MEXICO"=0,
                                            "NEW YORK"=0,
                                            "NORTH CAROLINA"=0,
                                            "NORTH DAKOTA"=0,
                                            "OHIO"=0,
                                            "OKLAHOMA"=0,
                                            "OREGON"=0,
                                            "PENNSYLVANIA"=0,
                                            "RHODE ISLAND"=0,
                                            "SOUTH CAROLINA"=0,
                                            "SOUTH DAKOTA"=0,
                                            "TENNESSEE"=0,
                                            "TEXAS"=0,
                                            "UTAH"=0,
                                            "VERMONT"=0,
                                            "VIRGINIA"=0,
                                            "WASHINGTON"=0,
                                            "WEST VIRGINIA"=0,
                                            "WYOMING"=0,
                                            "WISCONSIN"=0,
                                            "GUAM"=0, 
                                            "U.S.  VIRGIN ISLANDS"=0,
                                            "PUERTO RICO"=0))
nisALL3$CA<-as.numeric(as.character(nisALL3$CA))
nisALL3$POST<-ifelse(nisALL3$YEAR >= 2006, 1,0)
nisALL3$DIDCA <-nisALL3$POST*nisALL3$CA
DIDREG11 <- lm(BF_ENDR06 ~ POST + CA + DIDCA, data = nisALL3)
summary(DIDREG11) 


#COMBINED CA AND NJ
#uses nisALL4 
nisALL4$treat<- plyr::revalue(nisALL4$STATE, c("ALABAMA"= 0,
                                            "ALASKA"= 0,
                                            "ARIZONA"=0,
                                            "ARKANSAS"=0,
                                            "CALIFORNIA"=1,
                                            "COLORADO"=0,
                                            "CONNECTICUT"=0,
                                            "DELAWARE"=0,
                                            "DISTRICT OF COLUMBIA"=0,
                                            "FLORIDA"=0,
                                            "GEORGIA"=0,
                                            "HAWAII"=0,
                                            "IDAHO"=0,
                                            "ILLINOIS"=0,
                                            "INDIANA"=0,
                                            "IOWA"=0,
                                            "KANSAS"=0,
                                            "KENTUCKY"=0,
                                            "LOUISIANA"=0,
                                            "MAINE"=0,
                                            "MARYLAND"=0,
                                            "MASSACHUSETTS"=0,
                                            "MICHIGAN"=0,
                                            "MINNESOTA"=0,
                                            "MISSISSIPPI"=0,
                                            "MISSOURI"=0,
                                            "MONTANA"=0,
                                            "NEBRASKA"=0,
                                            "NEVADA"=0,
                                            "NEW HAMPSHIRE"=0,
                                            "NEW JERSEY"=1,
                                            "NEW MEXICO"=0,
                                            "NEW YORK"=0,
                                            "NORTH CAROLINA"=0,
                                            "NORTH DAKOTA"=0,
                                            "OHIO"=0,
                                            "OKLAHOMA"=0,
                                            "OREGON"=0,
                                            "PENNSYLVANIA"=0,
                                            "RHODE ISLAND"=0,
                                            "SOUTH CAROLINA"=0,
                                            "SOUTH DAKOTA"=0,
                                            "TENNESSEE"=0,
                                            "TEXAS"=0,
                                            "UTAH"=0,
                                            "VERMONT"=0,
                                            "VIRGINIA"=0,
                                            "WASHINGTON"=0,
                                            "WEST VIRGINIA"=0,
                                            "WYOMING"=0,
                                            "WISCONSIN"=0,
                                            "GUAM"=0, 
                                            "U.S.  VIRGIN ISLANDS"=0,
                                            "PUERTO RICO"=0))
nisALL4$DID5<-ifelse(nisALL4$YEAR >= 2006 &nisALL4$STATE=="CALIFORNIA" |
                     nisALL4$YEAR >= 2011 &nisALL4$STATE=="NEW JERSEY", 1,0)

nisALL4$DID6 <- as.factor(nisALL4$DID5)
nisALL4$treat <- as.factor(nisALL4$treat)
nisALL4$YEAR2 <- as.factor(nisALL4$YEAR)
DIDREG12 <- lm(BF_ENDR06 ~ YEAR2 + STATE + DID5, data = nisALL4)
summary(DIDREG12) 


nisPOV <- dplyr::filter(nisALL4, INCPOV1=="BELOW POVERTY")
nisPOV2 <- dplyr::filter(nisALL4, INCPOV1=="ABOVE POVERTY")
DIDREG14 <- lm(BF_ENDR06 ~ YEAR2 + STATE + DID5 + INCPOV1, data = nisALL4)
summary(DIDREG14) 